#MAILUSERNAME = 'light_black@126.com'
#MAILPASSWORD = 'fffffff77'	
#FLASKYADMIN  = 'light_black@126.com'
MAILUSERNAME = 'ffffffflv@gmail.com'
MAILPASSWORD = 'fffffff'
FLASKYADMIN  = 'light_black@126.com'